
### **❓ What is NumPy?**

**NumPy (Numerical Python)** is a powerful Python library used for **numerical computations**, especially with **multi-dimensional arrays and matrices**. It provides fast, memory-efficient array operations, and includes functions for mathematical, statistical, linear algebra, Fourier transforms, and more.


### **❓ Why use NumPy? (What problem does it solve?)**

Python lists are:

* Slow for numeric computations
* Limited in mathematical functionality
* Not memory-efficient
* Not suitable for large-scale numerical operations

**NumPy solves this by:**

* Offering high-performance operations via **C-backed arrays**
* Enabling **vectorized operations** (no explicit loops)
* Providing **broadcasting rules** to handle arrays of different shapes
* Supporting **matrix operations**, random number generation, and more

In short, NumPy is essential for scientific computing, data analysis, and machine learning workflows.


### **❓ How is NumPy better?**

**Compared to plain Python or lists:**

| Feature                  | Python Lists             | NumPy Arrays                 |
| ------------------------ | ------------------------ | ---------------------------- |
| Speed                    | Slow (interpreted)       | Fast (compiled in C)         |
| Memory                   | High usage               | Efficient (contiguous block) |
| Math Support             | Manual looping           | Vectorized functions         |
| Multi-dimensional Arrays | Complex (nested lists)   | Simple with `ndarray`        |
| Integration              | Weak with SciPy, ML libs | Core dependency for ML/DL    |

**NumPy is better** because it combines speed, simplicity, and functionality in numerical tasks — making it the **foundation of Python’s data science and machine learning stack**.



In [1]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2], [3, 4]])
a3 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)


In [2]:
a1

array([1, 2, 3])

In [3]:
a2

array([[1, 2],
       [3, 4]])

In [4]:
a3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
z1 = np.zeros(5)              # 1D array of zeros
z2 = np.zeros((2, 3))         # 2D array of shape 2x3
z3 = np.zeros((2, 2), dtype=int)


In [6]:
z1

array([0., 0., 0., 0., 0.])

In [7]:
z2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
z3

array([[0, 0],
       [0, 0]])

In [9]:
o1 = np.ones(4)
o2 = np.ones((3, 2))
o3 = np.ones((2, 2), dtype=bool)


In [11]:
o1

array([1., 1., 1., 1.])

In [12]:
o2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
o3

array([[ True,  True],
       [ True,  True]])

In [14]:
ar1 = np.arange(5)             # [0, 1, 2, 3, 4]
ar2 = np.arange(2, 10, 2)      # [2, 4, 6, 8]
ar3 = np.arange(1.5, 5.5, 1.0) # [1.5, 2.5, 3.5, 4.5]


In [15]:
ar1

array([0, 1, 2, 3, 4])

In [16]:
ar2

array([2, 4, 6, 8])

In [17]:
ar3

array([1.5, 2.5, 3.5, 4.5])

In [18]:
l1 = np.linspace(0, 1, 5)          # 5 values from 0 to 1
l2 = np.linspace(10, 50, 9)        # 9 values between 10 and 50
l3 = np.linspace(-1, 1, 3, endpoint=False)  # Without including 1


In [19]:
l1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
l2

array([10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [21]:
l3

array([-1.        , -0.33333333,  0.33333333])

In [22]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

s = arr.shape        # (2, 3)
t = arr.size         # 6
d = arr.dtype        # dtype('int64')
n = arr.ndim         # 2


In [23]:
s

(2, 3)

In [24]:
t

6

In [25]:
d

dtype('int64')

In [26]:
n

2

In [27]:
a = np.linspace(0, 9, 10).reshape(2, 5)
print(a.shape)       # (2, 5)
print(a.ndim)        # 2
print(a.size)        # 10
print(a.dtype)       # float64


(2, 5)
2
10
float64


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
x1 = arr[0, 0]     # 1
x2 = arr[1, 2]     # 6
x3 = arr[-1, -2]   # 5


In [29]:
x1

np.int64(1)

In [30]:
x2

np.int64(6)

In [31]:
x3

np.int64(5)

In [32]:
arr1 = np.arange(12).reshape(3, 4)
arr2 = np.arange(6).reshape(2, 3)
arr3 = np.reshape(np.arange(9), (3, 3))


In [33]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])